name: Assemble

on:
  push:
    branches:
      - master
      - remotecontrolling

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.JKS_FILE }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}

        run: |
          echo $ENCODED_STRING | base64 -d > "$SIGNING_KEY_STORE_PATH"
          

      - name: Assemble release
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.JKS_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.JKS_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Run lint for release
        run: ./gradlew lintRelease

      - name: Assemble debug
        run: ./gradlew assembleDebug

      - name: Run lint for debug
        run: ./gradlew lintDebug

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results-*.*
          

      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk


      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk 
          
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
